### ISSUE TITLE
@SelfValidation methods in base class are not recognised

### ISSUE THREAD

**Issue by dave1e6** [dropwizard/dropwizard#2336]
I have a base class with some general validations that apply to all subclasses and so I would like do the following:
```
@SelfValidating
public class BaseClass {
    @SelfValidation
    public void appliesToAllSubclasses(ViolationCollector collector) {
    }
}

public class SubClass extends BaseClass {
}
```

I expected that validating an instance of SubClass would call BaseClass.appliesToAllSubClasses, it doesn't and I get the following message in the logs:
```
08:16:45.188 [main] ERROR io.dropwizard.validation.selfvalidating.SelfValidatingValidator - The class class SubClass is annotated with @SelfValidating but contains no valid methods that are annotated with @SelfValidation
```

```
    @Test
    public void selfValidatingSubclass() {
        BaseClass baseClass = new SubClass();
        Validator validator = Validation.buildDefaultValidatorFactory().getValidator();
        validator.validate(baseClass);
    }
```

If I annotate SubClass with @SelfValidating as well then I get two log messages rather than one.

**Comment by manuel-hegner** [comment]
I fixed the inheritance problem but I am not sure in which case the problem with two log messages occurs. @dave1e6  Could you give me a test case (maybe based on my PR #2344) that shows that problem?

**Comment by nickbabcock** [comment]
Closing this as #2344 was merged. If the problem wasn't resolved, please reply with more info. Thanks @manuel-hegner for the implementation.

**Comment by isaki** [comment]
The issue still remains for a specific corner case. I will look into putting together some tests to reproduce it and possibly submit a PR to fix it (or at least share the tests so someone else can fix it if I can't find the time to patch it in the near term).

**Comment by manuel-hegner** [comment]
If you can write a test for this corner case or describe it well enough I will write the fix, no problem.

**Comment by isaki** [comment]
I can get you a pretty simple object model to use to reproduce it fairly quickly. I should have some time today to dedicate to this. I'll reply back in a bit.

**Comment by isaki** [comment]
I've broken down the problematic classes into three simple cases (you really only need two, but my original issue involved 3, so I've left it that way).

1) A base abstract class that contains the primary validation method.
2) One or more child classes that implement an extended validation method.

I'm sure this isn't the best design. Ideally I'd like to just hit each class with its own `@SelfValidating` method and have them all be run down the entire hierarchy. My workaround has each class overriding the base class `validate` and invoking `super.validate`.

Anyway, here is a super simplified version of what triggered the issue:

**Base Class**

```Java
package io.isaki.jsandbox.svtest;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.dropwizard.validation.selfvalidating.SelfValidation;
import io.dropwizard.validation.selfvalidating.ViolationCollector;

@JsonAutoDetect(
    getterVisibility = Visibility.NONE,
    creatorVisibility = Visibility.NONE,
    isGetterVisibility = Visibility.NONE,
    fieldVisibility = Visibility.NONE,
    setterVisibility = Visibility.NONE)
abstract class AbstractExample {

    @JsonProperty("s")
    private final String s;

    protected AbstractExample() {
        super();
        this.s = null;
    }

    protected AbstractExample(final String s) {
        super();
        this.s = Objects.requireNonNull(s);
    }

    @SelfValidation
    public final void validate(final ViolationCollector collector) {
        if (this.s == null) {
            collector.addViolation("s value cannot be null");
        }

        this.extendedValidation(collector);
    }

    public final String getS() {
        return this.s;
    }

    protected abstract void extendedValidation(final ViolationCollector collector);
}
```

**Implementations**

```Java
package io.isaki.jsandbox.svtest;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.dropwizard.validation.selfvalidating.SelfValidating;
import io.dropwizard.validation.selfvalidating.ViolationCollector;

@SelfValidating
public final class ImplOne extends AbstractExample {

    @JsonProperty("x")
    private final int x;

    /**
     * Serialization constructor.
     */
    @SuppressWarnings("unused")
    private ImplOne() {
        super();
        this.x = 0;
    }

    public ImplOne(final String s, final int x) {
        super(s);
        if (x < 1) {
            throw new IllegalArgumentException();
        }

        this.x = x;
    }

    public int getX() {
        return this.x;
    }

    @Override
    protected void extendedValidation(final ViolationCollector collector) {
        if (this.x < 1) {
            collector.addViolation("x must be at least 1");
        }
    }
}
```

```Java
package io.isaki.jsandbox.svtest;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.dropwizard.validation.selfvalidating.SelfValidating;
import io.dropwizard.validation.selfvalidating.ViolationCollector;

@SelfValidating
public final class ImplTwo extends AbstractExample {

    @JsonProperty("c")
    private final char c;

    /**
     * Serialization constructor.
     */
    @SuppressWarnings("unused")
    private ImplTwo() {
        super();
        this.c = 0;
    }

    public ImplTwo(final String s, final char c) {
        super(s);
        if (!validateC(c)) {
            throw new IllegalArgumentException();
        }

        this.c = c;
    }

    public char getC() {
        return this.c;
    }

    @Override
    protected void extendedValidation(final ViolationCollector collector) {
        if (!validateC(this.c)) {
            collector.addViolation("x must be at least 1");
        }
    }

    private static boolean validateC(final char c) {
        return c >= 'a' && c <= 'z';
    }
}
```

**Expected Behavior:**

Validation should occur on the child classes via the parent class method.

**Result:**

Exception thrown due to lack of `SelfValidation` annotation in child classes.

**Comment by isaki** [comment]
@manuel-hegner 

I've done more testing and got some interesting behaviors on DropWizard 1.3.9. There is a definite inconsistency with method/annotation inheritence and some outright bugs (I'm able to get violation to run multiple times).

Base class: Marked with `@SelfValidating` and has a `@SelfValidation` method.

**Scenario 1:**

Child class overrides said method and does not mark it with `@SelfValidation`. Child class is not marked with `@SelfValidating`.

Expected behavior: Undecided. This is probably OK, but see _Scenario 2_.
Result: No validation is invoked.

** Scenario 2:**

Child class overrides said method and marks it with `@SelfValidation`. Child class is not marked `@SelfValidating`.

Expected behavior: Given the behavior of _Scenario 1_, I would expect no validation to occur.
Result: Validation is performed correctly.

** Scenario 3:**

Child class overrides said method and marks it with `@SelfValidation`. Child class is marked as `@SelfValidating`.

Expected behavior: Validation is performed correctly.
Result: Validation is performed correctly... twice. This probably a bug. See _Scenario 5_ for a stranger manifestation of this issue.

** Scenario 4:**

Child class creates a separate validation method, marks it with `@SelfValidation`. Child class is not marked as `@SelfValidating`.

Expected behavior: Undecided, like _Scenario 1_.
Result: Validation is performed correctly.

** Scenario 5:**

Child class creates a separate validation method, marks it will `@SelfValidation`. Child class is marked as `@SelfValidating`.

Expected behavior: Either both the parent and child methods should be invoked or just the child (given previous scenarios, which I don't necessarily agree with). I prefer the first.
Result: The child's method is invoked twice. I'm going to go out on a limb and say this is absolutely a bug.

** Scenario 6:**

Child class has no self validation annotations.

Expected behavior: I don't even know at this point. I'd expect no validation to occur, but apparently `@SelfValidating` must be inherited by the child (see _Scenario 4_) so maybe I'd expect the parent's method to at least be invoked?
Result: No validation occurs.

** Scenario 7:**

Child class declares that it is `@SelfValidating` but does not actually have any methods marked with `@SelfValidation`.

Expected behavior: The parent method should be invoked. Or an exception. Or something.
Result: Nothing happens. No validation. No warnings. Nothing.

I will write up a proposal for what the expected behaviors should be and put together a test that exercises the various scenarios once we all agree.

**Comment by isaki** [comment]
Proposal:

| Parent @SelfValidating | Parent @SelfValidation | Child @SelfValidating | Child @SelfValidation           | Desired Behavior                                             |
| ---------------------- | ---------------------- | --------------------- | ------------------------------- | ------------------------------------------------------------ |
| None                   | Yes                    | NA                    | NA                              | Error on Parent                                              |
| Yes                    | No                     | NA                    | NA                              | Error on Parent                                              |
| Yes                    | Yes (concrete)         | No                    | No                              | Validator should use standard annotation validation; additionally it should run the validation method for the parent (or whatever class in the chain) |
| Yes                    | Yes (abstract)         | No                    | No                              | The validation method declared in the parent should be run; the child need not know that it has implemented the validation for the parent class and should not require annotations. Validator should use standard annotation for the child class and of its children for fields declared therein. |
| Yes                    | Yes (concrete)         | Yes                   | No                              | Error on Child                                               |
| Yes                    | Yes                    | No                    | Yes                             | Error on Child                                               |
| Yes                    | Yes                    | Yes                   | Yes, on distinct method         | Both parent and child annotated methods should be executed (if parent is abstract, there will be impl somewhere that gets invoked). |
| Yes                    | Yes                    | Yes                   | Yes, on override/implementation | The overridden/implemented method should be invoked once.    |

**Comment by isaki** [comment]
Should I put the proposal in a new issue or here @nickbabcock? If I'm putting it here can you please re-open this ticket? Thanks!
