### ISSUE TITLE
Upgrade Jetty to 9.4.18

### ISSUE THREAD

**Issue by gjvoosten** [dropwizard/dropwizard#2768]
Dropwizard `1.3.10` suffers from this bug: https://github.com/eclipse/jetty.project/issues/3550
After not using the server for a while, the admin port becomes unresponsive.
I know `1.3.10` was released because of #2745 so downgrading to `1.3.9` is not really an option (although there this particular Jetty bug is absent).
Can `1.3.11` (quickly I hope) be released with Jetty 9.4.18.v20190429 (basically, commit https://github.com/dropwizard/dropwizard/commit/4933a815e3109ba11fd24f1411286393eed37761 )?

**Comment by mattnelson** [comment]
In scenarios like this where there are transitive dependencies pulling in an undesired version. I use `dependencyManagement` to diverge from dropwizard to avoid being coupled to its release cycle.

Example of what I have in my POM which is modeled very similar to the dropwizard-bom.
https://github.com/dropwizard/dropwizard/blob/42759228412e484fa170bc9ab5aae019422432c3/dropwizard-bom/pom.xml#L25

Define the impacted jetty dependencies.
https://github.com/dropwizard/dropwizard/blob/42759228412e484fa170bc9ab5aae019422432c3/dropwizard-bom/pom.xml#L227-L334

**Comment by joschi** [comment]
Closed via 3500399b5b128f5988b6aaf6aa702ae1d1b56c5d.

**Comment by gjvoosten** [comment]
Verified that this issue is indeed resolved with release `1.3.11`. Thanks!

**Comment by psimonazzi** [comment]
After updating from `1.3.9` to `1.3.12` we still experience unresponsive connections on the http port after some idle time. Upstream issue eclipse/jetty.project#3550 was reopened, that's probably because of the same problem?
